config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get 'users/sign_up/:token' => 'registrations#new_from_token'
    get 'users' => 'home#index'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources 'downloaders'
  resources 'uploads'
  resources 'joinder_uploads'
  resources 'submissions'

  # Document management system disabled 
  # resources 'studies'
  # resources 'sites'
  # resources 'folders'

  patch 'save_submission_edit',  to: 'submissions#save_edit',             as: 'save_submission_edit'

  get  'edit_study_title/:id',   to: 'studies#edit_title',                as: 'edit_study_title'

  get  'study_docs/:id',         to: 'study_docs#index',                  as: 'study_docs'

  get  'thank_you',              to: 'home#thank_you',                    as: 'thank_you'
  get  'revise',                 to: 'home#revise',                       as: 'revise'
  get  'approved',               to: 'home#approved',                     as: 'approved'
  get  'rejected',               to: 'home#rejected',                     as: 'rejected'

  get  'download_upload/:id',    to: 'uploads#download',                  as: 'download_upload'
  get  'download_joinder/:id',   to: 'joinder_uploads#download',          as: 'download_joinder'

  get  'register_institution',   to: 'institutions#register',             as: 'register_institution'
  get  'save_registration',      to: 'institutions#register'
  post 'save_registration',      to: 'institutions#update'
  get  'json_institutions',      to: 'institutions#json_institutions'

  get  'offer_signatory',        to: 'downloads#offer_signatory',         as: 'offer_signatory'
  get  'download_signatory',     to: 'downloads#download_signatory',      as: 'download_signatory'
  get  'notify_signatory',       to: 'downloads#notify',                  as: 'notify_signatory'

  get  'fwa_search',             to: 'fwas#search' 
  get  'fwa_search_results',     to: 'fwas#search' 
  post 'fwa_search_results',     to: 'fwas#search_results'
  get  'fwa_select/:id',         to: 'fwas#select',                       as: 'fwa_select'
  get  'fwa_start',              to: 'fwas#start',                        as: 'fwa_start'
  get  'fwa_names',              to: 'fwas#names',                        as: 'fwa_names'
  get  'get_institution_names',  to: 'institutions#names',                as: 'institution_names'

  # ID is user-chosen FWA id
  get  'assign_institution/:id', to: 'users#assign_institution',          as: 'assign_institution'
  get  'complete_profile',       to: 'users#complete_profile',            as: 'complete_profile'
  post 'save_profile',           to: 'users#save_profile',                as: 'save_profile'
  get  'download_agreement',     to: 'users#download_agreement',          as: 'download_agreement'
  post 'contact',                to: 'users#contact',                     as: 'contact'
  post 'update_active',          to: 'users#update_active',               as: 'update_active'

  get  'admin',                  to: 'admin#index',                       as: 'admin'
  post 'invite',                 to: 'admin#invite',                      as: 'invite'

  post 'download',               to: 'downloaders#download',              as: 'download'
  post 'delete_downloader',      to: 'downloaders#delete',                as: 'delete_downloader'

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  extend ActsAsTree::TreeWalker
  acts_as_tree order: 'created_at DESC'

  validates :name, presence: true

  has_many :uploads
  belongs_to :site
  belongs_to :study

  # Return boolean indicating whether or not self is an admin folder
  # NOTE: This must be done differently if we add folder kinds other than study and admin
  def is_admin?
    !associated_study
  end

  # There should always be exactly 1 folder that meets these criteria
  # This folder is created by seeds.db
  def self.admin_root
    Folder.where(is_admin: true, parent_id: nil).first
  end

  # For any folder, return the associated study if there is one.
  def associated_study

    # For study root folders
    return self.study if self.study

    # For site root folders
    return self.site.study if self.site

    # For children of study folders or site folders
    folder = self.parent
    while folder
      return folder.study if folder.study
      return folder.site.study if folder.site
      folder = folder.parent
    end

    # For non-study-related folders (admin)
    return nil
  end

  # Return an array of all folders contained within self
  def all_child_folders
    folders = []
    self.walk_tree do |folder, level|
      folders << folder
    end
    folders
  end

  # Return an array of all uploads contained with in self and self's folders
  def all_child_uploads
    uploads = []
    self.uploads.each do |upload|
      uploads << upload
    end
    self.walk_tree do |folder, level|
      folder.uploads.each do |upload|
        uploads << upload
      end
    end
    uploads
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  before_action :check_read_access, only: [:show]
  before_action :check_write_access, except: [:show]

  # Create a new folder
  def create
    folder = Folder.new(folder_params)
    if folder.save
      # no-op
    else
      flash.alert = folder.errors.full_messages.join("<br>").html_safe
    end
    redirect_to :back
  end

  # Main document management interface
  def show
    @folder = Folder.find(params[:id])
    @writeable = current_user.can_write_to_folder?(@folder)
  end

  # Only used for renaming folders as of now
  def update
    @folder_params = folder_params
    @folder = Folder.find(@folder_params[:id])
    if @folder.update_attributes(@folder_params)
      # no-op
    else
      flash.alert = @folder.errors.full_messages.join("<br>").html_safe
    end
    # Rename is always done from within a parent folder
    redirect_to folder_path(@folder.parent.id)
  end

  # Destroys a folder and all of its children, folders and uploads
  def destroy
    folder = Folder.find(params[:id])
    folder.destroy
    folder.all_child_uploads.each {|u| u.destroy}
    folder.all_child_folders.each {|f| f.destroy}
    # Delete is always done from within a parent folder
    redirect_to folder_path(folder.parent.id)
  end

  private

  # Ensures that the current user has read access to the current folder
  def check_read_access
    redirect_to :back unless current_user.can_read_folder?(Folder.find(params[:id]))
  end

  # Ensures that the current user has write access to the current folder
  def check_write_access
    id = params[:id] || folder_params[:id] || folder_params[:parent_id]
    redirect_to :back unless current_user.can_write_to_folder?(Folder.find(id))
  end

  # Params whitelist
  def folder_params
    params.require(:folder).permit(:id, :name, :study_id, :site_id, :parent_id, :is_admin)
  end

end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_breadcrumbs.html.haml
.text-left.text-small.pad-left-20
  = link_to 'Studies', studies_path unless folder.is_admin?
  - this_folder = folder
  - folders = []
  - while folder.parent
    - folders << folder.parent
    - folder = folder.parent
  - folders = folders.reverse
  - folders.each do |folder|
    = '&nbsp;&nbsp;>&nbsp;&nbsp;'.html_safe unless this_folder.is_admin? && folder == Folder.admin_root
    = link_to folder.name, folder_path(folder.id)
  = '&nbsp;&nbsp;>&nbsp;&nbsp;'.html_safe unless this_folder == Folder.admin_root
  = this_folder.name

app/views/folders/_sidebar.html.haml
- study = folder.associated_study  
%ul.nav.nav-stacked.text-left.text-small
  - if writeable
    %li
      New
      %hr
    %ul
      %li
        = link_to image_tag('folder_plus.png'), '#', class: 'new-folder'
        = link_to 'Folder', '#', class: 'new-folder'
      %li{style: 'margin-top:5px;'}
        = link_to image_tag('file_plus.png'), '#', class: 'new-upload'
        = link_to ' File', '#', class: 'new-upload'
  - if study
    %li.pad-top-20
      Study Docs
      %hr
      %ul
        %li
          = link_to image_tag('folder_closed.png'), folder_path(study.root_folder.id)
          = link_to truncate(study.title, length: 28), folder_path(study.root_folder.id)
    - reviewing_site = study.reviewing_site
    - if reviewing_site && current_user.can_read_folder?(reviewing_site.root_folder)
      %li.pad-top-20
        Reviewing Site Docs
        %hr
      %ul
        %li
          = link_to image_tag('folder_closed.png'), folder_path(reviewing_site.root_folder.id)
          = link_to truncate(reviewing_site.institution.name, length: 28), folder_path(reviewing_site.root_folder.id)
    - if study.relying_sites
      %li.pad-top-20
        Relying Site Docs
        %hr
      - study.relying_sites.each do |site|
        %ul
          %li{style: 'margin-top: 5px;'}
            = link_to image_tag('folder_closed.png'), folder_path(site.root_folder.id)
            = link_to truncate(site.institution.name, length: 28), folder_path(site.root_folder.id)

app/views/folders/show.html.haml
= render 'breadcrumbs', folder: @folder 
.col-xs-12.col-sm-5.col-md-4.col-lg-3.well
  = render 'sidebar', folder: @folder, writeable: @writeable
.col-xs-12.col-sm-7.col-md-8.col-lg-9
  .docs-container.text-small
      
    .doc-item{style: 'text-align:center'}= @folder.name

    - if @writeable
      .doc-item#new-folder-form
        = form_for Folder.new, html: {style: 'display:inline'} do |f|
          = image_tag 'folder_closed.png'
          = f.hidden_field :parent_id, value: @folder.id
          = f.text_field :name, size: '30', placeholder: 'Name', id: 'new-folder-name'
          = f.submit 'Create'
        = button_tag 'Cancel', class: 'btn btn-primary', id: 'cancel-new-folder'

      .doc-item#new-upload-form
        = form_for Upload.new, html: {style: 'display:inline;', multipart: true} do |f|
          = image_tag 'file.png'
          = f.hidden_field :folder_id, value: @folder.id
          = f.hidden_field :kind, value: 'study'
          = f.file_field :doc, style: 'display:inline;margin-top:20px', id: 'file-select' 
          = f.submit 'Upload'
        = button_tag 'Cancel', class: 'btn btn-primary', id: 'cancel-new-upload'

    - if !@folder.children.first && !@folder.uploads.first
      .doc-item{style: 'text-align:center;'}
        Nothing here yet! 
        - if @writeable
          Use the New Folder or New File Links to Add Content.
        - else
          (You do not have write access to this folder.)

    - @folder.children.each do |folder|
      .doc-item
        = link_to image_tag('folder_closed.png'), folder_path(folder.id), class: 'folder-context-menu', id: "folder-#{folder.id}"
        = link_to folder.name, folder_path(folder.id),
          class: 'folder-link folder-context-menu',
          id: "folder-#{folder.id}",
          title: "Updated at #{format_date_time(folder.updated_at)}"
        
        %span.folder-rename-form{id: "folder-#{folder.id}"}
          = form_for folder, method: :patch, html: {style: 'display:inline'} do |f|
            = f.hidden_field :id, value: folder.id
            = f.text_field :name, class: 'folder-rename-text-field', id: "folder-#{folder.id}", size: 40
            = f.submit 'Rename'
          = button_tag 'Cancel', class: 'btn btn-primary cancel-folder-rename', id: "folder-#{folder.id}"

        = link_to 'Delete Folder', folder_path(folder.id), method: :delete, class: 'folder-delete-link',
          id: "folder-#{folder.id}", style: 'display:none',
          :data => {:confirm => "This will permanently delete #{folder.all_child_uploads.length} documents. Are you sure?"}

    - @folder.uploads.each do |upload|
      .doc-item
        = link_to image_tag('file.png'), download_upload_path(upload.id), class: 'upload-context-menu', id: "upload-#{upload.id}"
        = link_to upload.doc_file_name.truncate(40), download_upload_path(upload.id),
          class: 'upload-link upload-context-menu',
          id: "upload-#{upload.id}",
          title: "Updated at #{format_date_time(upload.updated_at)}"

        %span.upload-rename-form{id: "upload-#{upload.id}"}
          = form_for upload, method: :patch, html: {style: 'display:inline'} do |f|
            = f.hidden_field :id, value: upload.id
            = f.text_field :doc_file_name, class: 'upload-rename-text-field', id: "upload-#{upload.id}", size: 40
            = f.submit 'Rename'
          = button_tag 'Cancel', class: 'btn btn-primary cancel-upload-rename', id: "upload-#{upload.id}"

        = link_to 'Delete Upload', upload_path(upload.id), method: :delete, class: 'upload-delete-link',
          id: "upload-#{upload.id}", style: 'display:none',
          :data => {:confirm => "Are you sure that you want to permanently delete this document?"}

-# Hide the unhelpful Bootstrap help text in new upload form
:javascript
  $('.help-block').hide();