config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get 'users/sign_up/:token' => 'registrations#new_from_token'
    get 'users' => 'home#index'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources 'downloaders'
  resources 'uploads'
  resources 'joinder_uploads'
  resources 'submissions'

  # Document management system disabled 
  # resources 'studies'
  # resources 'sites'
  # resources 'folders'

  patch 'save_submission_edit',  to: 'submissions#save_edit',             as: 'save_submission_edit'

  get  'edit_study_title/:id',   to: 'studies#edit_title',                as: 'edit_study_title'

  get  'study_docs/:id',         to: 'study_docs#index',                  as: 'study_docs'

  get  'thank_you',              to: 'home#thank_you',                    as: 'thank_you'
  get  'revise',                 to: 'home#revise',                       as: 'revise'
  get  'approved',               to: 'home#approved',                     as: 'approved'
  get  'rejected',               to: 'home#rejected',                     as: 'rejected'

  get  'download_upload/:id',    to: 'uploads#download',                  as: 'download_upload'
  get  'download_joinder/:id',   to: 'joinder_uploads#download',          as: 'download_joinder'

  get  'register_institution',   to: 'institutions#register',             as: 'register_institution'
  get  'save_registration',      to: 'institutions#register'
  post 'save_registration',      to: 'institutions#update'
  get  'json_institutions',      to: 'institutions#json_institutions'

  get  'offer_signatory',        to: 'downloads#offer_signatory',         as: 'offer_signatory'
  get  'download_signatory',     to: 'downloads#download_signatory',      as: 'download_signatory'
  get  'notify_signatory',       to: 'downloads#notify',                  as: 'notify_signatory'

  get  'fwa_search',             to: 'fwas#search' 
  get  'fwa_search_results',     to: 'fwas#search' 
  post 'fwa_search_results',     to: 'fwas#search_results'
  get  'fwa_select/:id',         to: 'fwas#select',                       as: 'fwa_select'
  get  'fwa_start',              to: 'fwas#start',                        as: 'fwa_start'
  get  'fwa_names',              to: 'fwas#names',                        as: 'fwa_names'
  get  'get_institution_names',  to: 'institutions#names',                as: 'institution_names'

  # ID is user-chosen FWA id
  get  'assign_institution/:id', to: 'users#assign_institution',          as: 'assign_institution'
  get  'complete_profile',       to: 'users#complete_profile',            as: 'complete_profile'
  post 'save_profile',           to: 'users#save_profile',                as: 'save_profile'
  get  'download_agreement',     to: 'users#download_agreement',          as: 'download_agreement'
  post 'contact',                to: 'users#contact',                     as: 'contact'
  post 'update_active',          to: 'users#update_active',               as: 'update_active'

  get  'admin',                  to: 'admin#index',                       as: 'admin'
  post 'invite',                 to: 'admin#invite',                      as: 'invite'

  post 'download',               to: 'downloaders#download',              as: 'download'
  post 'delete_downloader',      to: 'downloaders#delete',                as: 'delete_downloader'

end

app/views/admin/_downloaders.html.haml
.row 
  .col-md-12
    %strong
      .text-left Click on a column header to sort
    .panel.panel-default.table-responsive
      %table.table.table-striped.sorted-table
        %thead
          %tr
            %th.small-text{style: 'border-top-left-radius:3px;border:none;'} Name
            %th.small-text{style: 'border:none;'} Email
            %th.small-text{style: 'border:none;'} Institution
            %th.small-text{style: 'border:none;'} Title
            %th.small-text{style: 'border:none;'} Invite / Invited At
            %th.small-text{style: 'border-top-right-radius:3px;border:none;'} Delete
        %tbody
          - Downloader.not_deleted.order('created_at DESC').all.each do |downloader|
            %tr
              %td.small-text= "#{downloader.first_name} #{downloader.last_name}"
              %td.small-text= downloader.email
              %td.small-text= downloader.institution_name
              %td.small-text= downloader.title
              - invite_link_text = !!downloader.invited_at ? 'Re-invite' : 'Invite'
              %td.small-text{'data-target': "#invite-#{downloader.id}", 'data-toggle': 'modal'}
                = format_date(downloader.invited_at) if downloader.invited_at
                = link_to invite_link_text, '#'
              = render 'invite_modal', downloader: downloader
              %td.small-text
                = form_for downloader, url: delete_downloader_path, method: 'post' do |f|
                  = f.hidden_field :id, value: downloader.id
                  = link_to 'Delete', nil, class: 'submit-downloader-delete', confirm: 'Balls'

app/views/admin/_institution_details.html.haml
.centered.pad-top-20
  = render 'institutions/form', institution: institution

app/views/admin/_institution_modal.html.haml
.modal.fade{id: "institution-#{institution.id}", 'aria-labelledby': 'modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog.modal-lg{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4#modal-label.modal-title= institution.name
      .modal-body
        = render 'institution_details', institution: institution
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/admin/_institutions.html.haml
.row 
  .col-md-12
    %strong
      .text-left Click on a column header to sort
    .panel.panel-default.table-responsive
      %table.table.table-striped.sorted-table
        %thead
          %tr
            %th.small-text{style: 'border-top-left-radius:3px;border:none;'} Institution
            %th.small-text{style: 'border:none;'} Created at
            %th.small-text{style: 'border:none;'} Created by
            %th.small-text{style: 'border:none;'} Status
            %th.small-text{style: 'border-top-right-radius:3px;border:none;'} Users
        %tbody
          - Institution.order('created_at DESC').all.each do |institution|
            %tr
              %td.small-text= institution.name
              %td.small-text= format_date(institution.created_at)
              - creator = User.find(institution.creating_user_id)
              %td.small-text= creator.email
              - status = institution.status
              - status = institution.submission.status if institution.submission
              %td.small-text= status.titleize
              %td.small-text= institution.users.count

app/views/admin/_invite_modal.html.haml
.modal.fade{id: "invite-#{downloader.id}", 'aria-labelledby': 'modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4#modal-label.modal-title Invite User to SMART IRB
      .modal-body
        = form_tag invite_path do
          = hidden_field_tag :id, downloader.id
          = submit_tag "Invite #{downloader.email} to SMART IRB"
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/admin/_notes_modal.html.haml
.modal.fade{id: "notes-#{submission.id}", 'aria-labelledby': 'modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4#modal-label.modal-title= submission.institution.name
      .modal-body
        %p.text-left
          %strong Notes for this submission:
        %p.text-left
          = form_for submission, url: submission_path(submission), method: 'patch', namespace: "notes_#{submission.id}" do |f|
            %p= f.text_area :notes, rows: 10, class: 'text_area', style: 'width: 100%'
            %p= f.submit 'Update Submission Notes'
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/admin/_review_modal.html.haml
.modal.fade{id: "review-#{submission.id}", 'aria-labelledby': 'modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4#modal-label.modal-title{style: 'padding:10px;'}= submission.institution.name
      .modal-body
        %p.text-left
          %strong Select the new status for this submission:
        %p.text-left
          = form_for submission, url: submission_path(submission), method: 'patch', namespace: "submission_#{submission.id}" do |f|
            = f.radio_button :status, 'needs_revision'
            = f.label :status, 'Needs Revision', value: 'needs_revision', style: 'font-weight: normal;'
            %br
            = f.radio_button :status, 'approved'
            = f.label :status, 'Activated', value: 'approved', style: 'font-weight: normal;'
            %br
            = f.radio_button :status, 'rejected'
            = f.label :status, 'Not Activated', value: 'rejected', style: 'font-weight: normal;'
            .status-change-email
              .centered
                %fieldset.form-fieldset{style: 'padding-bottom:0px;'}
                  %legend
                    %strong Email
                  %p.text-left
                    %strong This email will be sent to the institution's three identified contacts, and to the submitter. You will also recieve a copy.
                  - institution = submission.institution
                  %span{style: 'display:table-cell;'} To:
                  %p.text-left{style: 'display:table-cell;vertical-align:top;padding-left:4px;'}= "#{institution.poc_email}, #{institution.altpoc_email}, #{institution.io_email}, #{submission.submitter.email}"
                  %p.text-left= "Cc: #{current_user.email}"
                  %p.text-left= text_area_tag 'email_body', nil, rows: 10, placeholder: 'Type email body here.', required: true
              %p.text-center= f.submit 'Update Submission Status and Send Email'
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/admin/_stats.html.haml
.text-left.col-md-4
  .panel.panel-default
    %table.table.table-striped
      %th.small-text Submission Status
      %th.small-text Count
      %th.small-text.text-center Show
      %tr
        %td.small-text Under Review
        %td.small-text= Submission.where(status: 0).count
        %td.text-center= check_box_tag '', nil, true, class: 'submission_type_check_box', id: 'needs_review'
      %tr
        %td.small-text Needing Revision
        %td.small-text= Submission.where(status: 1).count
        %td.text-center= check_box_tag '', nil, true, class: 'submission_type_check_box', id: 'needs_revision'
      %tr
        %td.small-text Activated
        %td.small-text= Submission.where(status: 2).count
        %td.text-center= check_box_tag '', nil, true, class: 'submission_type_check_box', id: 'approved'
      %tr
        %td.small-text Not Activated
        %td.small-text= Submission.where(status: 3).count
        %td.text-center= check_box_tag '', nil, true, class: 'submission_type_check_box', id: 'rejected'
      %tr
        %td.small-text Total
        %td.small-text= Submission.count
        %td

app/views/admin/_submissions.html.haml
.row
  = render 'stats'
.row 
  .col-md-12
    %strong
      .text-left Click on a column header to sort
    .panel.panel-default.table-responsive
      %table.table.table-striped.sorted-table
        %thead
          %tr
            %th.small-text{style: 'border-top-left-radius:3px;border:none;'} Institution
            %th.small-text{style: 'border:none;'} Submitter
            %th.small-text{style: 'border:none;'} Submission
            %th.small-text{style: 'border:none;'} Submission Status
            %th.small-text{style: 'border:none;'} Last update
            %th.small-text{style: 'border:none;'} Internal Notes 
            %th.small-text{style: 'border-top-right-radius:3px;border:none;'} Approved By
        %tbody
          - Submission.order('updated_at DESC').all.each do |submission|
            %tr{class: submission.status}
              - institution = submission.institution
              %td.small-text{'data-target': "#institution-#{institution.id}", 'data-toggle': 'modal'}= link_to institution.name, '#'
              = render 'institution_modal', institution: institution
              - user = User.find(submission.created_by)
              %td.small-text{'data-target': "#user-#{user.id}", 'data-toggle': 'modal'}= link_to user.email, '#'
              = render 'user_modal', user: user
              %td.small-text= link_to truncate(submission.upload.doc_file_name, size: 40), download_joinder_path(submission.upload.id), target: '_blank'
              %td.small-text{'data-target': "#review-#{submission.id}", 'data-toggle': 'modal'}= link_to submission.status_label.titleize, '#'
              = render 'review_modal', submission: submission
              %td.small-text= format_date_time submission.updated_at
              %td.small-text{'data-target': "#notes-#{submission.id}", 'data-toggle': 'modal'}= link_to 'Notes', '#'
              = render 'notes_modal', submission: submission
              - if submission.approver_id
                %td.small-text= User.find(submission.approver_id).email
              - else
                %td

app/views/admin/_user_modal.html.haml
.modal.fade{id: "user-#{user.id}", 'aria-labelledby': 'modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4#modal-label.modal-title= "#{user.first_name} #{user.last_name}, #{user.degrees.upcase.gsub(',', ', ')}"
      .modal-body
        %p
          .text-left= user.email
          .text-left= user.phone
          .text-left= "Title: #{user.title}"
        %p
          .text-left= "Created at: #{format_date_time user.created_at}"
          .text-left= "Last Sign In: #{format_date_time user.last_sign_in_at if user.last_sign_in_at}"
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/admin/_users.html.haml
.row 
  .col-md-12
    %strong
      .text-left Click on a column header to sort
    .panel.panel-default.table-responsive
      %table.table.table-striped.sorted-table
        %thead
          %tr
            %th.small-text{style: 'border-top-left-radius:3px;border:none;'} Name
            %th.small-text{style: 'border:none;'} Role
            %th.small-text{style: 'border:none;'} Active
            %th.small-text{style: 'border:none;'} Email
            %th.small-text{style: 'border:none;'} Institution
            %th.small-text{style: 'border:none;'} Phone
            %th.small-text{style: 'border:none;'} Title
            %th.small-text{style: 'border-top-right-radius:3px;border:none;'} Degrees
        %tbody
          - User.order('created_at DESC').all.each do |user|
            %tr
              %td.small-text= truncate("#{user.first_name} #{user.last_name}", length: 30)
              %td.small-text= user.role.name.capitalize
              %td.small-text.text-center
                = form_for user, url: update_active_path, method: 'post' do |f|
                  = f.check_box :active, class: 'toggle-user-active', data: { user_id: user.id }, disabled: user == current_user
              %td.small-text= truncate(user.email, length: 30)
              %td.small-text= user.institution.try(:name)
              %td.small-text= truncate(user.phone, length: 30)
              %td.small-text= truncate(user.title, length: 30)
              %td.small-text= user.degrees.upcase.gsub(',', ', ') if user.degrees

app/views/admin/index.html.haml
%ul.nav.nav-tabs
  %li.active.tab
    %a{class: 'tab-link', 'data-toggle': 'tab', href: '#submissions'} Joinder Submissions
  %li.tab
    %a{class: 'tab-link', 'data-toggle': 'tab', href: '#institutions'} Institutions
  %li.tab
    %a{class: 'tab-link', 'data-toggle': 'tab', href: '#users'} Users
  %li.tab
    %a{class: 'tab-link', 'data-toggle': 'tab', href: '#downloaders'} Downloaders
.tab-content
  #submissions.tab-pane.active= render 'submissions'
  #institutions.tab-pane= render 'institutions'
  #users.tab-pane= render 'users'
  #downloaders.tab-pane= render 'downloaders'