config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get 'users/sign_up/:token' => 'registrations#new_from_token'
    get 'users' => 'home#index'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources 'downloaders'
  resources 'uploads'
  resources 'joinder_uploads'
  resources 'submissions'

  # Document management system disabled 
  # resources 'studies'
  # resources 'sites'
  # resources 'folders'

  patch 'save_submission_edit',  to: 'submissions#save_edit',             as: 'save_submission_edit'

  get  'edit_study_title/:id',   to: 'studies#edit_title',                as: 'edit_study_title'

  get  'study_docs/:id',         to: 'study_docs#index',                  as: 'study_docs'

  get  'thank_you',              to: 'home#thank_you',                    as: 'thank_you'
  get  'revise',                 to: 'home#revise',                       as: 'revise'
  get  'approved',               to: 'home#approved',                     as: 'approved'
  get  'rejected',               to: 'home#rejected',                     as: 'rejected'

  get  'download_upload/:id',    to: 'uploads#download',                  as: 'download_upload'
  get  'download_joinder/:id',   to: 'joinder_uploads#download',          as: 'download_joinder'

  get  'register_institution',   to: 'institutions#register',             as: 'register_institution'
  get  'save_registration',      to: 'institutions#register'
  post 'save_registration',      to: 'institutions#update'
  get  'json_institutions',      to: 'institutions#json_institutions'

  get  'offer_signatory',        to: 'downloads#offer_signatory',         as: 'offer_signatory'
  get  'download_signatory',     to: 'downloads#download_signatory',      as: 'download_signatory'
  get  'notify_signatory',       to: 'downloads#notify',                  as: 'notify_signatory'

  get  'fwa_search',             to: 'fwas#search' 
  get  'fwa_search_results',     to: 'fwas#search' 
  post 'fwa_search_results',     to: 'fwas#search_results'
  get  'fwa_select/:id',         to: 'fwas#select',                       as: 'fwa_select'
  get  'fwa_start',              to: 'fwas#start',                        as: 'fwa_start'
  get  'fwa_names',              to: 'fwas#names',                        as: 'fwa_names'
  get  'get_institution_names',  to: 'institutions#names',                as: 'institution_names'

  # ID is user-chosen FWA id
  get  'assign_institution/:id', to: 'users#assign_institution',          as: 'assign_institution'
  get  'complete_profile',       to: 'users#complete_profile',            as: 'complete_profile'
  post 'save_profile',           to: 'users#save_profile',                as: 'save_profile'
  get  'download_agreement',     to: 'users#download_agreement',          as: 'download_agreement'
  post 'contact',                to: 'users#contact',                     as: 'contact'
  post 'update_active',          to: 'users#update_active',               as: 'update_active'

  get  'admin',                  to: 'admin#index',                       as: 'admin'
  post 'invite',                 to: 'admin#invite',                      as: 'invite'

  post 'download',               to: 'downloaders#download',              as: 'download'
  post 'delete_downloader',      to: 'downloaders#delete',                as: 'delete_downloader'

end

app/models/downloader.rb
# A Downloader is a non-registered user who downloads the IRBrely agreement from an external public site
# Anyone on the Internet can be a Downloader. Some Downloaders are sent invitations to become Users by admin users.
class Downloader < ActiveRecord::Base

  validates :email, :first_name, :last_name, :title, :institution_name, presence: true, on: :create
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, if: '!self.email.blank?'
  validates_format_of :first_name, with: /\A[a-zA-Z  \.]+\Z/, if: '!first_name.blank?'
  validates_format_of :last_name, with: /\A[a-zA-Z \.]+\Z/, if: '!last_name.blank?'

  scope :not_deleted, -> { where(deleted_at: nil) }

end

app/controllers/downloaders_controller.rb
# This class contains methods for managing Downloaders
# NOTE: This controller is designed to be publically accessible and 
# its views are intended to be embedded on an external site.
class DownloadersController < ApplicationController
  skip_before_action :authenticate_user!, except: [:delete]
  before_action :only_admins, only: [:delete]
  after_action :allow_iframe

  # Layout has no top navbar - for embedding in informational website
  layout 'downloaders'

  # Instantiate a new Downloader
  def new
    @downloader = Downloader.new
  end

  # Save a new Downloader
  def create
    @downloader = Downloader.where(downloader_params).first_or_create
    @downloader.token = SecureRandom.hex(10)
    if verify_recaptcha(model: @downloader) && @downloader.save
      redirect_to downloader_path(@downloader.id)
    else
      flash.now.alert = @downloader.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  # Show downloader. Functions as thank you screen and context for JS
  # to trigger the actual download (see view).
  def show
    @downloader = Downloader.find(params[:id])
  end

  # Called via JS trigger in show view after create
  # Performs the actual download.
  def download
    downloader = Downloader.find(downloader_params[:id])
    downloader.update_attributes(downloaded_at: Time.now)
    send_file "#{Rails.root}/agreement/SMART_IRB_Agreement.pdf"
    AdminMailer.new_downloader(downloader).deliver_now
  end
  
  # Admins can "delete" a downloader (set deleted_at)
  def delete
    downloader = Downloader.find(downloader_params[:id])
    downloader.update_attributes(deleted_at: Time.now)
    flash.notice = 'Downloader deleted.'
    redirect_to :root
  end

  private

  # Params whitelist
  def downloader_params
    params.require(:downloader).permit(:id, :first_name, :last_name, :title, :email, :institution_name)
  end

  # Allows a specific website to embed content from this controller.
  def allow_iframe
    if Rails.env == 'production'
      response.headers['X-Frame-Options'] = 'ALLOW-FROM https://irbrely.org'
    else
      response.headers['X-Frame-Options'] = 'ALLOW-FROM https://ic3d-dev.dartmouth.edu'
    end
  end

end

app/helpers/downloaders_helper.rb
module DownloadersHelper
end

app/views/downloaders/create.html.haml
%h3 Thank you for downloading the agreement.

app/views/downloaders/new.html.haml
.white.big-text.pad-bottom-30 Download the SMART IRB Agreement
.white.pad-bottom-30.light-grey Thank you for your interest in SMART IRB.
.white.pad-bottom-30.light-grey Downloading the SMART IRB Agreement is the first step to joining SMART IRB. In general, IRB administrators or other research compliance personnel will be best suited to initiate this process, due to the nature of the information required in subsequent steps.
.white.pad-bottom-30.light-grey The appropriate human research protections officials at your institution should review the agreement prior to determining whether to join SMART IRB. Downloading the agreement does not obligate your institution to join SMART IRB, and simply joining SMART IRB  does not obligate an institution to participate in any research or reliance arrangement under the SMART IRB Agreement.
.white.pad-bottom-15 To download the SMART IRB agreement, please fill out the information below. All fields are required.
#form-container
  = bootstrap_form_for @downloader do |f|
    .row
      .col-md-4
        .field.pad-top-20
          = f.text_field :first_name, label: '', placeholder: 'First Name', class: 'downloader-validate', autofocus: true
      .col-md-4
        .field.pad-top-20
          = f.text_field :last_name, label: '', placeholder: 'Last Name', class: 'downloader-validate'
      .col-md-4
        .field.pad-top-20
          = f.text_field :email, label: '', placeholder: 'Email', class: 'downloader-validate'
    .row
      .col-md-4
        .field.pad-top-20
          = f.text_field :title, label: '', placeholder: 'Title at Institution', class: 'downloader-validate'
      .col-md-4
        .field.pad-top-20
          = f.text_field :institution_name, label: '', placeholder: 'Institution', class: 'typeahead downloader-validate'
      .col-md-4
    %div{style: 'width:303px;margin-left:auto;margin-right:auto;padding-top:20px;padding-bottom:20px;'}= recaptcha_tags
    %div.pad-top-20.text-center=f.submit 'Download', id: 'downloader-submit', disabled: true, style: 'background-color: #428bca !important;'
:javascript
  getFwaNames();

app/views/downloaders/show.html.haml
.white.big-text.text-center{style: 'padding-bottom: 30px;'} Thank you for downloading the SMART IRB agreement.
.white.big-text.text-center Please contact us if you have any questions.
#form-container
  = bootstrap_form_for @downloader, url: download_path, method: :post do |f|
    = f.hidden_field :id, value: @downloader.id
    = f.submit '', class: 'hidden', id: 'download-now'
:javascript
  $('#download-now').click();