config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get 'users/sign_up/:token' => 'registrations#new_from_token'
    get 'users' => 'home#index'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources 'downloaders'
  resources 'uploads'
  resources 'joinder_uploads'
  resources 'submissions'

  # Document management system disabled 
  # resources 'studies'
  # resources 'sites'
  # resources 'folders'

  patch 'save_submission_edit',  to: 'submissions#save_edit',             as: 'save_submission_edit'

  get  'edit_study_title/:id',   to: 'studies#edit_title',                as: 'edit_study_title'

  get  'study_docs/:id',         to: 'study_docs#index',                  as: 'study_docs'

  get  'thank_you',              to: 'home#thank_you',                    as: 'thank_you'
  get  'revise',                 to: 'home#revise',                       as: 'revise'
  get  'approved',               to: 'home#approved',                     as: 'approved'
  get  'rejected',               to: 'home#rejected',                     as: 'rejected'

  get  'download_upload/:id',    to: 'uploads#download',                  as: 'download_upload'
  get  'download_joinder/:id',   to: 'joinder_uploads#download',          as: 'download_joinder'

  get  'register_institution',   to: 'institutions#register',             as: 'register_institution'
  get  'save_registration',      to: 'institutions#register'
  post 'save_registration',      to: 'institutions#update'
  get  'json_institutions',      to: 'institutions#json_institutions'

  get  'offer_signatory',        to: 'downloads#offer_signatory',         as: 'offer_signatory'
  get  'download_signatory',     to: 'downloads#download_signatory',      as: 'download_signatory'
  get  'notify_signatory',       to: 'downloads#notify',                  as: 'notify_signatory'

  get  'fwa_search',             to: 'fwas#search' 
  get  'fwa_search_results',     to: 'fwas#search' 
  post 'fwa_search_results',     to: 'fwas#search_results'
  get  'fwa_select/:id',         to: 'fwas#select',                       as: 'fwa_select'
  get  'fwa_start',              to: 'fwas#start',                        as: 'fwa_start'
  get  'fwa_names',              to: 'fwas#names',                        as: 'fwa_names'
  get  'get_institution_names',  to: 'institutions#names',                as: 'institution_names'

  # ID is user-chosen FWA id
  get  'assign_institution/:id', to: 'users#assign_institution',          as: 'assign_institution'
  get  'complete_profile',       to: 'users#complete_profile',            as: 'complete_profile'
  post 'save_profile',           to: 'users#save_profile',                as: 'save_profile'
  get  'download_agreement',     to: 'users#download_agreement',          as: 'download_agreement'
  post 'contact',                to: 'users#contact',                     as: 'contact'
  post 'update_active',          to: 'users#update_active',               as: 'update_active'

  get  'admin',                  to: 'admin#index',                       as: 'admin'
  post 'invite',                 to: 'admin#invite',                      as: 'invite'

  post 'download',               to: 'downloaders#download',              as: 'download'
  post 'delete_downloader',      to: 'downloaders#delete',                as: 'delete_downloader'

end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :sites

  validates :title, presence: true

  def reviewing_site
    Site.where(study_id: self.id).where(reviewing: true).first
  end

  def relying_sites
    Site.where(study_id: self.id).where(reviewing: false).all
  end

  def root_folder
    Folder.where(study_id: self.id).first
  end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  before_filter :only_admins, except: [:index]

  # List existing studies
  def index
    if current_user.privileged?
      @studies = Study.all.order('created_at DESC')
    else
      @studies = current_user.institution.studies.order('created_at DESC')
    end
  end

  # Instantiate a new study
  def new
    @study = Study.new
  end

  # Save a new study
  def create
    @study = Study.new(study_params)
    if @study.save
      # NOTE: Create a root study folder every time a study is created
      folder = Folder.new
      folder.name = @study.title
      folder.study_id = @study.id
      folder.save
      redirect_to new_site_path(study_id: @study.id)
    else
      flash.now.alert = @study.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  # Save changes to a study
  def update
    @study = Study.find(study_params[:id])
    if @study.update_attributes(study_params)
      redirect_to edit_study_path(id: @study.id)
    else
      flash.now.alert = @study.errors.full_messages.join("<br>").html_safe
      # NOTE: This needs to be more sophisiticated if updates other than title are added.
      render :edit_title
    end
  end

  # Render study edit view (includes new site form)
  def edit
    @study = Study.find(params[:id])
    @institution_names = Institution.approved.order(:name).map {|i| i.name}
    @study.sites.each do |site|
      @institution_names.delete(site.institution.name)
    end
    redirect_to new_site_path(study_id: params[:id]) unless @study.reviewing_site
  end

  # Edit study title
  def edit_title
    @study = Study.find(params[:id])
  end

  private

  # Params whitelist
  def study_params
    params.require(:study).permit(:id, :title)
  end

end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/edit.html.haml
%h3.margin-bottom-20
  = @study.title
  = link_to "<span style='font-size:18px;', class='fa fa-pencil'></span>".html_safe, edit_study_title_path(@study.id)
- reviewing_site = @study.reviewing_site
- if reviewing_site
  %h4.margin-bottom-20.text-left
    = "Reviewing Site: #{reviewing_site.try(:institution).try(:name)}"
    = link_to "<span class='fa fa-pencil'></span>".html_safe, edit_site_path(reviewing_site.id)
- relying_sites = @study.relying_sites
- if relying_sites.first
  %h4.text-left Relying Sites:
  .margin-bottom-20
    - relying_sites.each do |site|
      .text-left.pad-left-40
        = site.institution.name
        = button_to site_path(site.id), method: :delete, class: 'icon-button', onclick: 'return confirm("Are you sure? This will delete the site and all associated documents!")' do
          <span class='fa fa-trash-o'></span>
  
.text-left
  = link_to 'Add a relying site for this study', '#', class: 'btn btn-primary', id: 'reveal-new-site', style: 'margin-top: 5px;'
  = link_to 'Done editing this study', studies_path, class: 'btn btn-primary', style: 'margin-top: 5px;'
#new-relying-site{style: 'display:none;'}
  = bootstrap_form_for Site.new, html: {class: 'text-left'}  do |f|
    = f.hidden_field :study_id, value: @study.id
    = f.hidden_field :reviewing, value: 0
    = f.label :institution, 'Relying Site'
    = f.select :institution, options_for_select(@institution_names), placeholder: 'Institution Name', include_blank: true
    = f.submit 'Add Site'

:javascript
  getApprovedInstitutionNames();

app/views/studies/edit_title.html.haml
= bootstrap_form_for @study, url: study_path, method: :put, html: {class: 'text-left'}  do |f|
  = f.hidden_field :id, value: @study.id
  = f.label :title, 'New Study Title'
  = f.text_field :title
  = f.submit 'Save'

app/views/studies/index.html.haml
.row
  .col-xs-12
    .text-left.center-block
      - if current_user.privileged?
        %p= link_to 'Create a new study', new_study_path, class: 'btn btn-primary margin-bottom-20'
      - else
        %p.text-center To have a new study created, please contact SMART IRB staff using the Contact link above.
      %strong
        - if current_user.privileged?
          Existing Studies
        - else
          = "Studies Including #{current_user.institution.name}"
      .panel.panel-default.table-responsive
        %table.table.table-striped.sorted-table
          %thead
            %tr
              %th.small-text{style: 'border-top-left-radius:3px;border:none;'}
                Title
                - if current_user.privileged?
                  (click to edit)
              %th.small-text{style: 'border:none;'} Documents (click to manage)
              %th.small-text{style: 'border:none;'} Created
              %th.small-text{style: 'border:none;'} Reviewing institution
              %th.small-text{style: 'border-top-right-radius:3px;border:none;'} Relying institutions
          %tbody
            - @studies.each do |study|
              %tr
                - if current_user.privileged?
                  %td.small-text= link_to study.title, edit_study_path(study.id)
                - else
                  %td.small-text= study.title
                %td.small-text.text-center= link_to image_tag('folder_closed.png'), folder_path(study.root_folder.id)
                %td.small-text= format_date(study.created_at)
                %td.small-text= study.reviewing_site.try(:institution).try(:name)
                %td.small-text= study.relying_sites.count

app/views/studies/new.html.haml
%h3 New Study
= bootstrap_form_for @study, html: {class: 'text-left'}  do |f|
  = f.label :title, 'Study Title'
  = f.text_field :title
  = f.submit 'Continue'